stages:
  - build
  - update-manifest

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/manager
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

# --- ЭТАП 1: СБОРКА И ПУШ ---
build-manager:
  stage: build
  tags:
    - local-wsl
  script:
    - echo "Авторизация в реестре..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Сборка Docker-образа $IMAGE_NAME:$IMAGE_TAG"
    - cd manager
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

# --- ЭТАП 2: ОБНОВЛЕНИЕ YAML В GIT ---
update-k8s-manifest:
  stage: update-manifest
  tags:
    - local-wsl
  script: |
    echo "Обновление тега в k8s/manager.yaml на $IMAGE_TAG"
    sed -i "s|image: $CI_REGISTRY_IMAGE/manager:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" k8s/manager.yaml
    
    git config --global user.email "ci-bot@gitlab.com"
    git config --global user.name "GitLab CI Bot"
    
    git add k8s/manager.yaml
    git commit -m "chore(ci):update manager image to $IMAGE_TAG [skip ci]"
    git push https://oauth2:${CI_PUSH_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git HEAD:main
  only:
    - main
  needs:
    - build-manager