apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: prod
stringData:
    postgres-password: ENC[AES256_GCM,data:mkdTENkGOStd4Q==,iv:tR9ydVO0ZLF6kZ6PDuV2ztnxKuwJQfAOuPGr72D04mI=,tag:qFNlMAhECcrjWvknvLFZuA==,type:str]
    hy-password: ENC[AES256_GCM,data:IRwh5UacEVX0bUdTd2nIeTp+/Za3Slqn30R9CVo=,iv:0gyFZNriZ8guv9vc9GaYiiLjHCfRx7+/wOIbbqVL4kw=,tag:iLq+05dYIMtq4DdTDom5gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tz37eevuxl99ufulc4zxwh7ylnvnmcqe6v930d387mcllsc724esteuap4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbzRqYVFVaWlXTGU4elZG
            MDVVVUhKNmFPeWZSQU43bVZVQngvbWd3U1I0CllIbHZacDhGRnNKeFFJSW5TcHZx
            R3hUcWZlc1I3MTBDY2FieHpiN21qdFkKLS0tIEtUeTdzd1cxZHJWSUJTVXQ2bngz
            dERzQkllNVZaRy9qdDBQTWp3bnBlRmsKJI7u0tZYvLFvyVClEVCq00fz631gdQs8
            6eHFoVN6uQWlgW5kmL7kuJ8BblQsJH0Xynlohsf5t7ydk1eYe4uw4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T19:04:12Z"
    mac: ENC[AES256_GCM,data:OVUK2RNRtFjMbM8O4XcIVqK3leVnqlrSoyKwA0a1kDVIQ8xleOlIjVlkokq2CmtThxD1/m1n+jf5GMfXoZ7qTAcqME9Hh9YNqJEMQfwq+LfuSks7BHNR8ZBfIbOUKSBG7Q+dG8GcgEDxK7Wu2hOtkud/Yb7Utp0hvdoOycju8VU=,iv:apFyYR0eSsvtsPunnbgV9P9fz1BolSNMU2RrHNYSzlk=,tag:pZfZDsz8chVVkf8/jPbdJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: telegram-secret
    namespace: prod
stringData:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:Xi6KRydUsT76XWqwpZ2IOLoMzDeZOw20+GJvsqKXKgafAri3H8q4hVUKDAcKbQ==,iv:Wt9fLYC0+j++HnZQvuR0NYO37ou+Zx64auKl9jaXO5g=,tag:ypfnvA5rQtl+9ralucDStw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tz37eevuxl99ufulc4zxwh7ylnvnmcqe6v930d387mcllsc724esteuap4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbzRqYVFVaWlXTGU4elZG
            MDVVVUhKNmFPeWZSQU43bVZVQngvbWd3U1I0CllIbHZacDhGRnNKeFFJSW5TcHZx
            R3hUcWZlc1I3MTBDY2FieHpiN21qdFkKLS0tIEtUeTdzd1cxZHJWSUJTVXQ2bngz
            dERzQkllNVZaRy9qdDBQTWp3bnBlRmsKJI7u0tZYvLFvyVClEVCq00fz631gdQs8
            6eHFoVN6uQWlgW5kmL7kuJ8BblQsJH0Xynlohsf5t7ydk1eYe4uw4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T19:04:12Z"
    mac: ENC[AES256_GCM,data:OVUK2RNRtFjMbM8O4XcIVqK3leVnqlrSoyKwA0a1kDVIQ8xleOlIjVlkokq2CmtThxD1/m1n+jf5GMfXoZ7qTAcqME9Hh9YNqJEMQfwq+LfuSks7BHNR8ZBfIbOUKSBG7Q+dG8GcgEDxK7Wu2hOtkud/Yb7Utp0hvdoOycju8VU=,iv:apFyYR0eSsvtsPunnbgV9P9fz1BolSNMU2RrHNYSzlk=,tag:pZfZDsz8chVVkf8/jPbdJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
