apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets-sync
  namespace: prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: yandex-lockbox-cluster
    kind: ClusterSecretStore
  target:
    name: app-secrets # ИМЯ СЕКРЕТА, КОТОРОЕ ЖДУТ ТВОИ ПОДЫ
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: app-secrets-storage
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-secret-sync
  namespace: prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: yandex-lockbox-cluster
    kind: ClusterSecretStore
  target:
    name: telegram-secret # ИМЯ СЕКРЕТА ДЛЯ БОТА
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: telegram-bot-storage