apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager-sa
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: manager-sa
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 0
    #   maxUnavailable: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      hostNetwork: true # Нужно, чтобы достучаться до 127.0.0.1:8443 (Xray)
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: manager-sa
      containers:
      - name: manager
        image: registry.gitlab.com/i.rusakov7887/auto-sec-gateway/manager:78cf334-1776352941
        ports:
        - containerPort: 8080
        env:
        # 1. Достаем пароль из секрета (он не светится в Git)
        - name: DB_PASS_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        # 2. Собираем строку, которую ждет твой main.go
        - name: DATABASE_URL
          value: "host=postgres-service.prod.svc user=manager password=$(DB_PASS_SECRET) dbname=manager port=5432 sslmode=disable"
        - name: DB_HOST
          value: "postgres-service.prod.svc" # Это не секрет, можно оставить здесь
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: TELEGRAM_TOKEN
        - name: SUBSCRIPTION_BASE_URL
          value: "http://158.160.40.150"
        - name: SHORT_ID
          value: "abcdef12" # Это можно оставить открытым
        - name: ADMIN_ID
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: ADMIN_ID
        - name: PUBLIC_IP
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PUBLIC_IP
        - name: XRAY_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: XRAY_ADDR
        - name: XRAY_SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: XRAY_SERVER_NAME
              optional: true
        # Выносим ключи Xray в переменные окружения
        - name: XRAY_UUID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: xray-uuid
        - name: XRAY_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: xray-privkey
        - name: XRAY_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: xray-pubkey
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: prod
spec:
  selector:
    app: manager
  ports:
  - port: 80 # Порт, который будет слушать Сервис
    targetPort: 8080 # Порт твоей программы на Go