apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  # Настройки Postgres
  POSTGRES_USER: "manager"
  POSTGRES_DB: "manager"
  # Настройки сети
  PUBLIC_IP: "158.160.40.150"
  XRAY_ADDR: "127.0.0.1:8443"