apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # ЭТО ГЛОБАЛЬНЫЙ РЕСУРС
metadata:
  name: yandex-lockbox-cluster # НИКАКИХ NAMESPACE ЗДЕСЬ
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth-key
          key: key.json
          namespace: external-secrets # А это ссылка, ГДЕ искать ключ. Тут namespace нужен.