apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: config-templater
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - "apk add --no-cache gettext && envsubst < /template/xray-config.template.json > /etc/xray/config.json"
        env:
        - name: XRAY_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: xray-privkey
        volumeMounts:
        - name: template-volume
          mountPath: /template
        - name: config-volume
          mountPath: /etc/xray
      containers:
      - name: xray
        image: teddysun/xray:latest
        ports:
        - containerPort: 8443
          hostPort: 8443
        volumeMounts:
        - name: config-volume
          mountPath: /etc/xray
      volumes:
      - name: template-volume
        configMap:
          name: xray-template-cm
      - name: config-volume
        emptyDir: {}