apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sync
  namespace: flux-system
spec:
  interval: 1m
  path: "./k8s/overlays/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      DOMAIN: "auto-sec-gateway.duckdns.org"
      PUBLIC_IP: "31.76.96.91"
      EMAIL: "i.rusakov7887@gmail.com"
      POSTGRES_USER: "manager"
      POSTGRES_DB: "manager"