apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/marienbaum77/auto-sec-gateway/manager:50188864a26f9c68f2b8ecaacbd4137f1c25f381
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASS_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: PUBLIC_IP
          value: "${PUBLIC_IP}"
        - name: DOMAIN
          value: "${DOMAIN}"
              
        - name: DATABASE_URL
          value: "host=postgres-service.prod.svc user=$(POSTGRES_USER) password=$(DB_PASS_SECRET) dbname=$(POSTGRES_DB) port=5432 sslmode=disable"
        
        - name: SUBSCRIPTION_BASE_URL
          value: "https://$(DOMAIN):8443"

        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: TELEGRAM_TOKEN
        - name: ADMIN_ID
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: ADMIN_ID
        - name: HYSTERIA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: hy-password
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: prod
spec:
  selector:
    app: manager
  ports:
  - port: 80
    targetPort: 8080