apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- secrets-dev.yaml
images:
- name: ghcr.io/marienbaum77/auto-sec-gateway/manager
  newName: ghcr.io/marienbaum77/auto-sec-gateway/manager
  newTag: dev
