name: Deploy Manager

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manager/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Переводим имя пользователя в нижний регистр для Docker
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          TAG=${{ github.sha }}
          IMAGE_NAME=ghcr.io/$REPO_OWNER/auto-sec-gateway/manager:$TAG
          
          cd manager
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Update Kubernetes manifest
        run: |
          TAG=${{ github.sha }}
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$REPO_OWNER/auto-sec-gateway/manager:$TAG
          
          # Меняем старый образ на новый в YAML
          sed -i "s|image: .*manager:.*|image: $IMAGE_NAME|g" k8s/manager.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manager image to ${{ github.sha }} [skip ci]"
          file_pattern: 'k8s/manager.yaml'